##  cluster settings

# id: <id of the cluster to be created>
id: spark_cluster

# vm_size: <vm-size, see available options here: https://azure.microsoft.com/en-us/pricing/details/virtual-machines/linux/>
vm_size: standard_a2

# size: <number of dedicated nodes in the cluster, not that clusters must contain all dedicated or all low priority nodes>
size: 2

# size_low_pri: <number of low priority nodes in the cluster, mutually exclusive with size setting>


# username: <username for the linux user to be created> (optional)
username: spark

# docker_repo: <name of docker image repo (for more information, see https://github.com/Azure/thunderbolt/blob/master/docs/12-docker-image.md)>
docker_repo: jiata/thunderbolt:0.1.0-spark2.2.0-python3.5.4

# custom_script: <path to custom script to run on each node> (optional)


# wait: <true/false>
wait: true

# Provide a list of ports to open on the master node.
ports:
#   - 7777 # THis will open the port 7777 on docker image and map it to 7777 on the node
